### ISSUE TITLE
Crash when attempting to open  computer and drone

### ISSUE THREAD

**Issue by simion314** [ninnghazad/dronetest#5]
I am using the 0.4.10-dev version  and I get this error s when I attempt to open a drone, 
is this a version issue or something wrong with my installation?
I will try to read the source code and see if is something I can do,maybe understand what is heppening.
http://i.imgur.com/V27xSyU.png

**Comment by ninnghazad** [comment]
Closing this now because it's old and probably doesn't apply anymore.
